#-------------------------------------------------
#
# Project created by QtCreator 2014-04-15T07:57:59
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = PlotOfFall
TEMPLATE = app

FORMS    += Dialog.ui

QWT_LOCATION = C:/Qwt-6.1.0
INCLUDEPATH += $${QWT_LOCATION}/include
LIBS = -L$${QWT_LOCATION}/lib \
     -lqwtd

INCLUDEPATH += "C:/bullet/src"

LIBS += "C:/bullet/lib/libBullet.a"

SOURCES += main.cpp\
        Dialog.cpp \
    Simulation.cpp

HEADERS  += Dialog.h \
    Simulation.h \
    C:/bullet/src/Bullet3Collision/BroadPhaseCollision/shared/b3Aabb.h \
    C:/bullet/src/Bullet3Collision/BroadPhaseCollision/b3BroadphaseCallback.h \
    C:/bullet/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.h \
    C:/bullet/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.h \
    C:/bullet/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPair.h \
    C:/bullet/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhSubtreeInfoData.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhTraversal.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ClipFaces.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3Collidable.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3Contact4Data.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactConvexConvexSAT.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactSphereSphere.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ConvexPolyhedronData.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3FindConcaveSatAxis.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3FindSeparatingAxis.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3MprPenetration.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3NewContactReduction.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3QuantizedBvhNodeData.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ReduceContacts.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3RigidBodyData.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/shared/b3UpdateAabbs.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/b3Config.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/b3Contact4.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/b3RaycastInfo.h \
    C:/bullet/src/Bullet3Collision/NarrowPhaseCollision/b3RigidBodyCL.h \
    C:/bullet/src/Bullet3Common/shared/b3Float4.h \
    C:/bullet/src/Bullet3Common/shared/b3Int2.h \
    C:/bullet/src/Bullet3Common/shared/b3Int4.h \
    C:/bullet/src/Bullet3Common/shared/b3Mat3x3.h \
    C:/bullet/src/Bullet3Common/shared/b3PlatformDefinitions.h \
    C:/bullet/src/Bullet3Common/shared/b3Quat.h \
    C:/bullet/src/Bullet3Common/b3AlignedAllocator.h \
    C:/bullet/src/Bullet3Common/b3AlignedObjectArray.h \
    C:/bullet/src/Bullet3Common/b3CommandLineArgs.h \
    C:/bullet/src/Bullet3Common/b3HashMap.h \
    C:/bullet/src/Bullet3Common/b3Logging.h \
    C:/bullet/src/Bullet3Common/b3Matrix3x3.h \
    C:/bullet/src/Bullet3Common/b3MinMax.h \
    C:/bullet/src/Bullet3Common/b3PoolAllocator.h \
    C:/bullet/src/Bullet3Common/b3QuadWord.h \
    C:/bullet/src/Bullet3Common/b3Quaternion.h \
    C:/bullet/src/Bullet3Common/b3Random.h \
    C:/bullet/src/Bullet3Common/b3Scalar.h \
    C:/bullet/src/Bullet3Common/b3StackAlloc.h \
    C:/bullet/src/Bullet3Common/b3Transform.h \
    C:/bullet/src/Bullet3Common/b3TransformUtil.h \
    C:/bullet/src/Bullet3Common/b3Vector3.h \
    C:/bullet/src/Bullet3Dynamics/ConstraintSolver/b3ContactSolverInfo.h \
    C:/bullet/src/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.h \
    C:/bullet/src/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.h \
    C:/bullet/src/Bullet3Dynamics/ConstraintSolver/b3JacobianEntry.h \
    C:/bullet/src/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.h \
    C:/bullet/src/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.h \
    C:/bullet/src/Bullet3Dynamics/ConstraintSolver/b3SolverBody.h \
    C:/bullet/src/Bullet3Dynamics/ConstraintSolver/b3SolverConstraint.h \
    C:/bullet/src/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.h \
    C:/bullet/src/Bullet3Dynamics/shared/b3ContactConstraint4.h \
    C:/bullet/src/Bullet3Dynamics/shared/b3ConvertConstraint4.h \
    C:/bullet/src/Bullet3Dynamics/shared/b3Inertia.h \
    C:/bullet/src/Bullet3Dynamics/shared/b3IntegrateTransforms.h \
    C:/bullet/src/Bullet3Dynamics/b3CpuRigidBodyPipeline.h \
    C:/bullet/src/Bullet3Geometry/b3AabbUtil.h \
    C:/bullet/src/Bullet3Geometry/b3ConvexHullComputer.h \
    C:/bullet/src/Bullet3Geometry/b3GeometryUtil.h \
    C:/bullet/src/Bullet3Geometry/b3GrahamScan2dConvexHull.h \
    C:/bullet/src/Bullet3Serialize/Bullet2FileLoader/autogenerated/bullet2.h \
    C:/bullet/src/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.h \
    C:/bullet/src/Bullet3Serialize/Bullet2FileLoader/b3Chunk.h \
    C:/bullet/src/Bullet3Serialize/Bullet2FileLoader/b3Common.h \
    C:/bullet/src/Bullet3Serialize/Bullet2FileLoader/b3Defines.h \
    C:/bullet/src/Bullet3Serialize/Bullet2FileLoader/b3DNA.h \
    C:/bullet/src/Bullet3Serialize/Bullet2FileLoader/b3File.h \
    C:/bullet/src/Bullet3Serialize/Bullet2FileLoader/b3Serializer.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btAxisSweep3.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btBroadphaseInterface.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btDbvt.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btDispatcher.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.h \
    C:/bullet/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btCollisionConfiguration.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btCollisionCreateFunc.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btCollisionObject.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btCollisionObjectWrapper.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btCollisionWorld.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btGhostObject.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btManifoldResult.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/btUnionFind.h \
    C:/bullet/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btBox2dShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btCapsuleShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btCollisionMargin.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btCompoundShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btConcaveShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btConeShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btConvex2dShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btConvexHullShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btConvexPolyhedron.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btCylinderShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btEmptyShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btMaterial.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btMultiSphereShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btOptimizedBvh.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btShapeHull.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btSphereShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btStaticPlaneShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btStridingMeshInterface.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btTetrahedronShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btTriangleBuffer.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btTriangleCallback.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btTriangleInfoMap.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btTriangleMesh.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btTriangleMeshShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btTriangleShape.h \
    C:/bullet/src/BulletCollision/CollisionShapes/btUniformScalingShape.h \
    C:/bullet/src/BulletCollision/Gimpact/btBoxCollision.h \
    C:/bullet/src/BulletCollision/Gimpact/btClipPolygon.h \
    C:/bullet/src/BulletCollision/Gimpact/btCompoundFromGimpact.h \
    C:/bullet/src/BulletCollision/Gimpact/btContactProcessing.h \
    C:/bullet/src/BulletCollision/Gimpact/btGenericPoolAllocator.h \
    C:/bullet/src/BulletCollision/Gimpact/btGeometryOperations.h \
    C:/bullet/src/BulletCollision/Gimpact/btGImpactBvh.h \
    C:/bullet/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h \
    C:/bullet/src/BulletCollision/Gimpact/btGImpactMassUtil.h \
    C:/bullet/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.h \
    C:/bullet/src/BulletCollision/Gimpact/btGImpactShape.h \
    C:/bullet/src/BulletCollision/Gimpact/btQuantization.h \
    C:/bullet/src/BulletCollision/Gimpact/btTriangleShapeEx.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_array.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_basic_geometry_operations.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_bitset.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_box_collision.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_box_set.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_clip_polygon.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_contact.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_geom_types.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_geometry.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_hash_table.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_linear_math.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_math.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_memory.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_radixsort.h \
    C:/bullet/src/BulletCollision/Gimpact/gim_tri_collision.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btConvexCast.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btPointCollector.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h \
    C:/bullet/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h \
    C:/bullet/src/BulletDynamics/Character/btCharacterControllerInterface.h \
    C:/bullet/src/BulletDynamics/Character/btKinematicCharacterController.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btConstraintSolver.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btContactConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btContactSolverInfo.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btFixedConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btGearConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btHingeConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btJacobianEntry.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btSliderConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btSolverBody.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btSolverConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btTypedConstraint.h \
    C:/bullet/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.h \
    C:/bullet/src/BulletDynamics/Dynamics/btActionInterface.h \
    C:/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h \
    C:/bullet/src/BulletDynamics/Dynamics/btDynamicsWorld.h \
    C:/bullet/src/BulletDynamics/Dynamics/btRigidBody.h \
    C:/bullet/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h \
    C:/bullet/src/BulletDynamics/Featherstone/btMultiBody.h \
    C:/bullet/src/BulletDynamics/Featherstone/btMultiBodyConstraint.h \
    C:/bullet/src/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.h \
    C:/bullet/src/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.h \
    C:/bullet/src/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.h \
    C:/bullet/src/BulletDynamics/Featherstone/btMultiBodyJointMotor.h \
    C:/bullet/src/BulletDynamics/Featherstone/btMultiBodyLink.h \
    C:/bullet/src/BulletDynamics/Featherstone/btMultiBodyLinkCollider.h \
    C:/bullet/src/BulletDynamics/Featherstone/btMultiBodyPoint2Point.h \
    C:/bullet/src/BulletDynamics/Featherstone/btMultiBodySolverConstraint.h \
    C:/bullet/src/BulletDynamics/MLCPSolvers/btDantzigLCP.h \
    C:/bullet/src/BulletDynamics/MLCPSolvers/btDantzigSolver.h \
    C:/bullet/src/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.h \
    C:/bullet/src/BulletDynamics/MLCPSolvers/btLemkeSolver.h \
    C:/bullet/src/BulletDynamics/MLCPSolvers/btMLCPSolver.h \
    C:/bullet/src/BulletDynamics/MLCPSolvers/btMLCPSolverInterface.h \
    C:/bullet/src/BulletDynamics/MLCPSolvers/btPATHSolver.h \
    C:/bullet/src/BulletDynamics/MLCPSolvers/btSolveProjectedGaussSeidel.h \
    C:/bullet/src/BulletDynamics/Vehicle/btRaycastVehicle.h \
    C:/bullet/src/BulletDynamics/Vehicle/btVehicleRaycaster.h \
    C:/bullet/src/BulletDynamics/Vehicle/btWheelInfo.h \
    C:/bullet/src/BulletSoftBody/btDefaultSoftBodySolver.h \
    C:/bullet/src/BulletSoftBody/btSoftBody.h \
    C:/bullet/src/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.h \
    C:/bullet/src/BulletSoftBody/btSoftBodyData.h \
    C:/bullet/src/BulletSoftBody/btSoftBodyHelpers.h \
    C:/bullet/src/BulletSoftBody/btSoftBodyInternals.h \
    C:/bullet/src/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h \
    C:/bullet/src/BulletSoftBody/btSoftBodySolvers.h \
    C:/bullet/src/BulletSoftBody/btSoftBodySolverVertexBuffer.h \
    C:/bullet/src/BulletSoftBody/btSoftRigidCollisionAlgorithm.h \
    C:/bullet/src/BulletSoftBody/btSoftRigidDynamicsWorld.h \
    C:/bullet/src/BulletSoftBody/btSoftSoftCollisionAlgorithm.h \
    C:/bullet/src/BulletSoftBody/btSparseSDF.h \
    C:/bullet/src/clew/clew.h \
    C:/bullet/src/LinearMath/btAabbUtil2.h \
    C:/bullet/src/LinearMath/btAlignedAllocator.h \
    C:/bullet/src/LinearMath/btAlignedObjectArray.h \
    C:/bullet/src/LinearMath/btConvexHull.h \
    C:/bullet/src/LinearMath/btConvexHullComputer.h \
    C:/bullet/src/LinearMath/btDefaultMotionState.h \
    C:/bullet/src/LinearMath/btGeometryUtil.h \
    C:/bullet/src/LinearMath/btGrahamScan2dConvexHull.h \
    C:/bullet/src/LinearMath/btHashMap.h \
    C:/bullet/src/LinearMath/btIDebugDraw.h \
    C:/bullet/src/LinearMath/btList.h \
    C:/bullet/src/LinearMath/btMatrix3x3.h \
    C:/bullet/src/LinearMath/btMatrixX.h \
    C:/bullet/src/LinearMath/btMinMax.h \
    C:/bullet/src/LinearMath/btMotionState.h \
    C:/bullet/src/LinearMath/btPolarDecomposition.h \
    C:/bullet/src/LinearMath/btPoolAllocator.h \
    C:/bullet/src/LinearMath/btQuadWord.h \
    C:/bullet/src/LinearMath/btQuaternion.h \
    C:/bullet/src/LinearMath/btQuickprof.h \
    C:/bullet/src/LinearMath/btRandom.h \
    C:/bullet/src/LinearMath/btScalar.h \
    C:/bullet/src/LinearMath/btSerializer.h \
    C:/bullet/src/LinearMath/btStackAlloc.h \
    C:/bullet/src/LinearMath/btTransform.h \
    C:/bullet/src/LinearMath/btTransformUtil.h \
    C:/bullet/src/LinearMath/btVector3.h \
    C:/bullet/src/btBulletCollisionCommon.h \
    C:/bullet/src/btBulletDynamicsCommon.h
